version: 2.1


            
jobs:
  build-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-dep]
      - run:
          name: Build front-end
          command: |
            cd front-end
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-dep

  build-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-deps]
      - run:
          name: Back-end build
          command: |
            cd back-end
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-deps

 
            

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      
